[package]
name = "cmd_fontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
computer_vision = { path = ".." }
image = "0.24.1"

[profile.dev]
opt-level = 1
overflow-checks = false